name: Deploy to EC2

on:
  push:
    branches: [ main, master ]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Navigate to your project directory
          cd /home/ubuntu/webiLink/backend
          
          # Pull latest changes
          git pull origin main
          
          # Stop and remove current container
          docker stop webilink-container || true
          docker rm webilink-container || true
          
          # Remove old image to free up space
          docker rmi webilink-backend:latest || true
          
          # Build new image
          docker build -t webilink-backend:latest .
          
          # Run new container with same name and settings
          docker run -d \
            --name webilink-container \
            --restart unless-stopped \
            -p 5000:5000 \
            --env-file .env \
            webilink-backend:latest
          
          # Wait for container to start
          sleep 15
          
          # Check if container is running
          docker ps | grep webilink-container
          
          # Check application health
          # curl -f http://localhost:5000/health || echo "Health check endpoint not available"
          
          # Show recent logs
          docker logs --tail=20 webilink-container